app1/urls.py
from app1.views import *

from django.urls import path

app_name='somthing'

urlpatterns=[
    path('hansi/',hansi,name='hansi'),
]

app2/urls.py
from app2.views import *
from django.urls import path

app_name='anything'

urlpatterns=[
    path('bablu/',bablu,name='bablu'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
import app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def hansi(request):
    return render(request,'hansi.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def bablu(request):
    return render(request,'bablu.html')

templates/bablu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hey hansi i am fine</h1>
        <h1>yaa because i have headace so am looking dull</h1>
        <a href="{% url 'somthing:hansi' %}"><h1>hansi reyaction</h1></a>
    </center>
</body>
</html>

templates/hansi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hey bablu wt happend to u</h1>
        <h1>u looking so dull</h1>
        <a href="{% url 'anything:bablu' %}"><h1>bablu responce</h1></a>
    </center>
</body>
</html>